// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxLBEE7jGHfLtkRdsSxydWa0SEi9Df3zI',
    appId: '1:413198671972:web:075e4e213fb1dc8413bf71',
    messagingSenderId: '413198671972',
    projectId: 'mobprojnourish',
    authDomain: 'mobprojnourish.firebaseapp.com',
    storageBucket: 'mobprojnourish.firebasestorage.app',
    measurementId: 'G-3RNWS9GDTK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNGHU_BAfrWGocJO_UvxQ6yGVDdq-9K7Q',
    appId: '1:413198671972:ios:459aca1b5c3a876513bf71',
    messagingSenderId: '413198671972',
    projectId: 'mobprojnourish',
    storageBucket: 'mobprojnourish.firebasestorage.app',
    iosBundleId: 'com.example.proj',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNGHU_BAfrWGocJO_UvxQ6yGVDdq-9K7Q',
    appId: '1:413198671972:ios:459aca1b5c3a876513bf71',
    messagingSenderId: '413198671972',
    projectId: 'mobprojnourish',
    storageBucket: 'mobprojnourish.firebasestorage.app',
    iosBundleId: 'com.example.proj',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_ZQI09ytX25zcCDVrxiRiTyD152vHNL4',
    appId: '1:413198671972:android:f1db8d84c8fba1b413bf71',
    messagingSenderId: '413198671972',
    projectId: 'mobprojnourish',
    storageBucket: 'mobprojnourish.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxLBEE7jGHfLtkRdsSxydWa0SEi9Df3zI',
    appId: '1:413198671972:web:5d6ac7cd7bb8708f13bf71',
    messagingSenderId: '413198671972',
    projectId: 'mobprojnourish',
    authDomain: 'mobprojnourish.firebaseapp.com',
    storageBucket: 'mobprojnourish.firebasestorage.app',
    measurementId: 'G-2TGEYQ2CCH',
  );

}