import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'routes/app_routes.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'package:proj/services/firestore_service.dart';
import 'package:proj/services/auth_service.dart';
import 'package:proj/services/database_service.dart';
import 'package:camera/camera.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:proj/screens/camera_screen.dart';
import 'firebase_options.dart'; // Will be generated by FlutterFire CLI

List<CameraDescription> cameras = [];

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase
  // Note: This requires running `flutterfire configure` first to generate firebase_options.dart
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    print('Firebase initialization failed (expected if not configured): $e');
  }

  // Initialize cameras (only on mobile platforms, not web)
  if (!kIsWeb) {
    try {
      cameras = await availableCameras();
    } catch (e) {
      print('Error initializing cameras: $e');
    }
  }

  if (!kIsWeb) {
    final storageStatus = await Permission.storage.status;
    if (!storageStatus.isGranted) {
      await Permission.storage.request();
    }
  }

  runApp(
    MultiProvider(
      providers: [
        Provider<FirestoreService>(
          create: (_) => FirestoreService(),
        ),
        Provider<AuthService>(
          create: (_) => AuthService(),
        ),
        Provider<DatabaseService>(
          create: (_) => DatabaseService(),
        ),
      ],
      child: MyApp(cameras: cameras),
    ),
  );
}

class MyApp extends StatelessWidget {
  final List<CameraDescription> cameras;

  const MyApp({super.key, required this.cameras});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Nourish',
      theme: ThemeData(
        primarySwatch: Colors.green,
        fontFamily: 'Arial',
      ),
      initialRoute: AppRoutes.welcome, 
      routes: AppRoutes.routes,
      onGenerateRoute: (settings) {
        // Handle camera route with cameras argument
        if (settings.name == AppRoutes.camera) {
          return MaterialPageRoute(
            builder: (context) => CameraScreen(cameras: cameras),
          );
        }
        return null;
      },
    );
  }
  
}
