import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:app_links/app_links.dart';
import 'dart:async';
import 'routes/app_routes.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'package:proj/services/firestore_service.dart';
import 'package:proj/services/auth_service.dart';
import 'package:proj/services/database_service.dart';
import 'package:proj/services/data_seeder.dart';
import 'package:camera/camera.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:proj/screens/camera_screen.dart';
import 'firebase_options.dart'; // Will be generated by FlutterFire CLI

List<CameraDescription> cameras = [];

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await dotenv.load(fileName: ".env");
  // Initialize Firebase
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    print('✅ Firebase initialized successfully');

    // Auto-seed database with Egyptian data
    try {
      await DataSeeder.seed();
    } catch (e) {
      print('⚠️  Seeding skipped or failed: $e');
    }
  } catch (e) {
    print('Firebase initialization failed (expected if not configured): $e');
  }

  // Initialize cameras (only on mobile platforms, not web)
  if (!kIsWeb) {
    try {
      cameras = await availableCameras();
    } catch (e) {
      print('Error initializing cameras: $e');
    }
  }

  if (!kIsWeb) {
    final storageStatus = await Permission.storage.status;
    if (!storageStatus.isGranted) {
      await Permission.storage.request();
    }
  }

  runApp(
    MultiProvider(
      providers: [
        Provider<FirestoreService>(create: (_) => FirestoreService()),
        Provider<AuthService>(create: (_) => AuthService()),
        Provider<DatabaseService>(create: (_) => DatabaseService()),
      ],
      child: MyApp(cameras: cameras),
    ),
  );
}

final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

class MyApp extends StatefulWidget {
  final List<CameraDescription> cameras;

  const MyApp({super.key, required this.cameras});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late AppLinks _appLinks;
  StreamSubscription<Uri>? _linkSubscription;

  @override
  void initState() {
    super.initState();
    _initDeepLinks();
  }

  @override
  void dispose() {
    _linkSubscription?.cancel();
    super.dispose();
  }

  Future<void> _initDeepLinks() async {
    _appLinks = AppLinks();

    // Check initial link
    try {
      final Uri? initialLink = await _appLinks.getInitialLink();
      if (initialLink != null) {
        _handleDeepLink(initialLink);
      }
    } catch (e) {
      print('Error getting initial link: $e');
    }

    // Listen for new links
    _linkSubscription = _appLinks.uriLinkStream.listen(
      (Uri? uri) {
        if (uri != null) {
          _handleDeepLink(uri);
        }
      },
      onError: (err) {
        print('Error listening to links: $err');
      },
    );
  }

  void _handleDeepLink(Uri uri) {
    print('🔗 Deep link received: $uri');
    if (uri.host == 'paymob-success' || uri.path.contains('paymob-success')) {
      // Navigate to success screen
      navigatorKey.currentState?.pushNamedAndRemoveUntil(
        AppRoutes.paymobSuccess,
        (route) => false,
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: navigatorKey,
      debugShowCheckedModeBanner: false,
      title: 'Nourish',
      theme: ThemeData(
        primarySwatch: Colors.green,
        fontFamily: 'Arial',
        pageTransitionsTheme: PageTransitionsTheme(
          builders: {
            TargetPlatform.android: _CustomPageTransitionBuilder(),
            TargetPlatform.iOS: _CustomPageTransitionBuilder(),
            TargetPlatform.windows: _CustomPageTransitionBuilder(),
            TargetPlatform.macOS: _CustomPageTransitionBuilder(),
          },
        ),
      ),
      initialRoute: AppRoutes.splash,
      routes: AppRoutes.routes,
      onGenerateRoute: (settings) {
        // Handle camera route with cameras argument
        if (settings.name == AppRoutes.camera) {
          return MaterialPageRoute(
            builder: (context) => CameraScreen(cameras: widget.cameras),
          );
        }
        return null;
      },
    );
  }
}

class _CustomPageTransitionBuilder extends PageTransitionsBuilder {
  @override
  Widget buildTransitions<T>(
    PageRoute<T> route,
    BuildContext context,
    Animation<double> animation,
    Animation<double> secondaryAnimation,
    Widget child,
  ) {
    return SlideTransition(
      position: Tween<Offset>(begin: const Offset(1.0, 0.0), end: Offset.zero)
          .animate(
            CurvedAnimation(parent: animation, curve: Curves.easeInOutQuart),
          ),
      child: child,
    );
  }
}
